version: "3.9"

services:
  mariaDb:
    container_name: mariaDb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events7
    networks:
      - default
    ports:
      - 5050:5050
    restart: unless-stopped

networks:
  default:
    driver: bridge
