version: '3'

services:

  mariaDb:
    container_name: mariaDb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events7
    networks:
      - default
    ports:
      - 3306:3306
    # restart: unless-stopped

networks:
  default:
    driver: bridge
